# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_world/v1/greeter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from resemble.v1alpha1 import options_pb2 as resemble_dot_v1alpha1_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1chello_world/v1/greeter.proto\x12\x0ehello_world.v1\x1a\x1fresemble/v1alpha1/options.proto\"!\n\x0cGreeterState\x12\x11\n\tgreetings\x18\x02 \x03(\t\"\x12\n\x10GreetingsRequest\"&\n\x11GreetingsResponse\x12\x11\n\tgreetings\x18\x01 \x03(\t\" \n\x0cGreetRequest\x12\x10\n\x08greeting\x18\x01 \x01(\t\"!\n\rGreetResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t2\xc5\x01\n\x07Greeter\x12X\n\tGreetings\x12 .hello_world.v1.GreetingsRequest\x1a!.hello_world.v1.GreetingsResponse\"\x06\x82\xb5\x18\x02\n\x00\x12L\n\x05Greet\x12\x1c.hello_world.v1.GreetRequest\x1a\x1d.hello_world.v1.GreetResponse\"\x06\x82\xb5\x18\x02\x12\x00\x1a\x12\x82\xb5\x18\x0e\n\x0cGreeterStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_world.v1.greeter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GREETER._options = None
  _GREETER._serialized_options = b'\202\265\030\016\n\014GreeterState'
  _GREETER.methods_by_name['Greetings']._options = None
  _GREETER.methods_by_name['Greetings']._serialized_options = b'\202\265\030\002\n\000'
  _GREETER.methods_by_name['Greet']._options = None
  _GREETER.methods_by_name['Greet']._serialized_options = b'\202\265\030\002\022\000'
  _globals['_GREETERSTATE']._serialized_start=81
  _globals['_GREETERSTATE']._serialized_end=114
  _globals['_GREETINGSREQUEST']._serialized_start=116
  _globals['_GREETINGSREQUEST']._serialized_end=134
  _globals['_GREETINGSRESPONSE']._serialized_start=136
  _globals['_GREETINGSRESPONSE']._serialized_end=174
  _globals['_GREETREQUEST']._serialized_start=176
  _globals['_GREETREQUEST']._serialized_end=208
  _globals['_GREETRESPONSE']._serialized_start=210
  _globals['_GREETRESPONSE']._serialized_end=243
  _globals['_GREETER']._serialized_start=246
  _globals['_GREETER']._serialized_end=443
# @@protoc_insertion_point(module_scope)
