// @generated by protoc-gen-es v1.3.1
// @generated from file hello_world/v1/greeter.proto (package hello_world.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message hello_world.v1.GreeterState
 */
export const GreeterState = proto3.makeMessageType(
  "hello_world.v1.GreeterState",
  () => [
    { no: 2, name: "greetings", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message hello_world.v1.GreetingsRequest
 */
export const GreetingsRequest = proto3.makeMessageType(
  "hello_world.v1.GreetingsRequest",
  [],
);

/**
 * @generated from message hello_world.v1.GreetingsResponse
 */
export const GreetingsResponse = proto3.makeMessageType(
  "hello_world.v1.GreetingsResponse",
  () => [
    { no: 1, name: "greetings", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message hello_world.v1.GreetRequest
 */
export const GreetRequest = proto3.makeMessageType(
  "hello_world.v1.GreetRequest",
  () => [
    { no: 1, name: "greeting", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message hello_world.v1.GreetResponse
 */
export const GreetResponse = proto3.makeMessageType(
  "hello_world.v1.GreetResponse",
  () => [
    { no: 1, name: "greeting", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

