// @generated by protoc-gen-es v1.3.1
// @generated from file hello_world/v1/greeter.proto (package hello_world.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message hello_world.v1.GreeterState
 */
export declare class GreeterState extends Message<GreeterState> {
  /**
   * @generated from field: repeated string greetings = 2;
   */
  greetings: string[];

  constructor(data?: PartialMessage<GreeterState>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "hello_world.v1.GreeterState";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GreeterState;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GreeterState;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GreeterState;

  static equals(a: GreeterState | PlainMessage<GreeterState> | undefined, b: GreeterState | PlainMessage<GreeterState> | undefined): boolean;
}

/**
 * @generated from message hello_world.v1.GreetingsRequest
 */
export declare class GreetingsRequest extends Message<GreetingsRequest> {
  constructor(data?: PartialMessage<GreetingsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "hello_world.v1.GreetingsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GreetingsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GreetingsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GreetingsRequest;

  static equals(a: GreetingsRequest | PlainMessage<GreetingsRequest> | undefined, b: GreetingsRequest | PlainMessage<GreetingsRequest> | undefined): boolean;
}

/**
 * @generated from message hello_world.v1.GreetingsResponse
 */
export declare class GreetingsResponse extends Message<GreetingsResponse> {
  /**
   * @generated from field: repeated string greetings = 1;
   */
  greetings: string[];

  constructor(data?: PartialMessage<GreetingsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "hello_world.v1.GreetingsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GreetingsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GreetingsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GreetingsResponse;

  static equals(a: GreetingsResponse | PlainMessage<GreetingsResponse> | undefined, b: GreetingsResponse | PlainMessage<GreetingsResponse> | undefined): boolean;
}

/**
 * @generated from message hello_world.v1.GreetRequest
 */
export declare class GreetRequest extends Message<GreetRequest> {
  /**
   * E.g. "Hello, World".
   *
   * @generated from field: string greeting = 1;
   */
  greeting: string;

  constructor(data?: PartialMessage<GreetRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "hello_world.v1.GreetRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GreetRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GreetRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GreetRequest;

  static equals(a: GreetRequest | PlainMessage<GreetRequest> | undefined, b: GreetRequest | PlainMessage<GreetRequest> | undefined): boolean;
}

/**
 * @generated from message hello_world.v1.GreetResponse
 */
export declare class GreetResponse extends Message<GreetResponse> {
  /**
   * @generated from field: string greeting = 1;
   */
  greeting: string;

  constructor(data?: PartialMessage<GreetResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "hello_world.v1.GreetResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GreetResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GreetResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GreetResponse;

  static equals(a: GreetResponse | PlainMessage<GreetResponse> | undefined, b: GreetResponse | PlainMessage<GreetResponse> | undefined): boolean;
}

